import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
// import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ClientWrapper from "./client-wrapper";
import StoreInitializer from "@/components/StoreInitializer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";

// const geistSans = GeistSans;

// const geistMono = GeistMono;

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Groceria App",
  icons: {
    icon: "/assets/logo-short.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${PoppinsFont.variable} antialiased`}>
        <Script
          id="midtrans-snap"
          type="text/javascript"
          src={process.env.NEXT_PUBLIC_MIDTRANS_SNAP_URL}
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
        />
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <ClientWrapper>
            <StoreInitializer />
            {children}
            <ToastContainer
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </ClientWrapper>
        </ThemeProvider>
        <div id="map-portal-root"></div>
      </body>
    </html>
  );
}
